name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Clear Gradle cache
        run: |
          echo "Clearing Gradle caches..."
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/daemon
          rm -rf ~/.gradle/native
          rm -rf ~/.gradle/wrapper

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build Release APK
        run: cd android && ./gradlew assembleRelease

      - name: Show APK size
        run: |
          OUTPUT_FILE=apk-size.txt
          echo "APK size details" > $OUTPUT_FILE
          APK_PATH=$(find android/app/build/outputs/apk/release -name "*.apk" | head -n 1)
          ls -lh "$APK_PATH" >> $OUTPUT_FILE
          echo -e "\nTotal APK size:" >> $OUTPUT_FILE
          du -h "$APK_PATH" >> $OUTPUT_FILE
          cat $OUTPUT_FILE
