name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode Debug Keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > android/app/my-debug-key.jks

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build Signed Debug APK
        run: |
          cd android
          ./gradlew assembleDebug \
            -PMYAPP_UPLOAD_STORE_FILE=my-debug-key.jks \
            -PMYAPP_UPLOAD_KEY_ALIAS=$KEY_ALIAS \
            -PMYAPP_UPLOAD_STORE_PASSWORD=$KEYSTORE_PASSWORD \
            -PMYAPP_UPLOAD_KEY_PASSWORD=$KEY_PASSWORD

      - name: Build Signed Debug AAB
        run: |
          cd android
          ./gradlew bundleDebug \
            -PMYAPP_UPLOAD_STORE_FILE=my-debug-key.jks \
            -PMYAPP_UPLOAD_KEY_ALIAS=$KEY_ALIAS \
            -PMYAPP_UPLOAD_STORE_PASSWORD=$KEYSTORE_PASSWORD \
            -PMYAPP_UPLOAD_KEY_PASSWORD=$KEY_PASSWORD

      - name: Show APK size
        run: |
          OUTPUT_FILE=apk-size.txt
          APK_PATH=$(find android/app/build/outputs/apk/debug -name "*.apk" | head -n 1)
          if [ -f "$APK_PATH" ]; then
            echo "APK size details" > $OUTPUT_FILE
            ls -lh "$APK_PATH" >> $OUTPUT_FILE
            echo -e "\nTotal APK size:" >> $OUTPUT_FILE
            du -h "$APK_PATH" >> $OUTPUT_FILE
            cat $OUTPUT_FILE
          else
            echo "No APK found!" > $OUTPUT_FILE
            cat $OUTPUT_FILE
          fi

      - name: Upload APK and AAB artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-builds
          path: |
            android/app/build/outputs/apk/debug/*.apk
            android/app/build/outputs/bundle/debug/*.aab
            apk-size.txt
