name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Clear Gradle cache (optional, can speed up clean builds)
      - name: Clear Gradle cache
        run: |
          echo "Clearing Gradle caches..."
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/daemon
          rm -rf ~/.gradle/native
          rm -rf ~/.gradle/wrapper

      # Step 4: Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x android/gradlew

      # Step 5: Build Release APK
      - name: Build Release APK
        run: cd android && ./gradlew assembleRelease

      # Step 6: Generate APK size report
      - name: Show APK size
        run: |
          OUTPUT_FILE=apk-size.txt
          APK_PATH=$(find android/app/build/outputs/apk/release -name "*.apk" | head -n 1)

          if [ -f "$APK_PATH" ]; then
            echo "APK size details" > $OUTPUT_FILE
            ls -lh "$APK_PATH" >> $OUTPUT_FILE
            echo -e "\nTotal APK size:" >> $OUTPUT_FILE
            du -h "$APK_PATH" >> $OUTPUT_FILE
            cat $OUTPUT_FILE
          else
            echo "No APK found!" > $OUTPUT_FILE
            cat $OUTPUT_FILE
          fi

      # Step 7: Upload APK and size report as artifacts
      - name: Upload APK and size report
        uses: actions/upload-artifact@v3
        with:
          name: apk-and-size-report
          path: |
            android/app/build/outputs/apk/release/*.apk
            apk-size.txt
